version: "3.8"
services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - REDIS_HOST=redis_db
      - NODE_ENV=development 
    links: 
      - redis_db
  redis_db:
    image: redis:3.2.8
    container_name: worker_redis
    expose: 
      - 6379