branch-defaults:
  $CIRCLE_BRANCH:
    environment: $EB_ENVIRONMENT
  feature/deploy:
    environment: worker-qa
environment-defaults:
  $EB_ENVIRONMENT:
    branch: null
    repository: null
  worker-qa:
    branch: null
    repository: null
global:
  application_name: worker
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Worker
