version: "3.8"
services:
  grafana:
    build:
      context: ./grafana
      args:
        buildno: 1
    links: 
      - influxdb
    ports: 
      - "3000:3000"
  influxdb:
    build:
      context: ./influxdb
      args:
        buildno: 1
    ports: 
      - "8086:8086"
  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
  telegraf:
    links:
        - influxdb
    build:
      context: ./telegraf
      args:
        buildno: 1
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"